language: python
sudo: false
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - ffmpeg
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt
  - travis_retry pip install python-coveralls
  - travis_retry python setup.py dev
script: py.test --runslow --cov-config=.coveragerc
after_success:
  - coveralls
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always